/** Exchange tickers behind Compass's shipped *real* sample brands (public facts) — seeded first. */
export const SAMPLE_TICKER_MAP = {
  'whole-foods': 'AMZN',
  kroger: 'KR',
  safeway: 'ACI',
  albertsons: 'ACI',
  walmart: 'WMT',
  target: 'TGT',
  costco: 'COST',
  starbucks: 'SBUX',
  mcdonalds: 'MCD',
  chipotle: 'CMG',
  'taco-bell': 'YUM',
  'yum-brands': 'YUM',
  shell: 'SHEL',
  'shell-plc': 'SHEL',
  exxonmobil: 'XOM',
  chevron: 'CVX',
  amazon: 'AMZN',
  'home-depot': 'HD',
  lowes: 'LOW',
  walgreens: 'WBA',
  'walgreens-boots-alliance': 'WBA',
  'cvs-pharmacy': 'CVS',
  'cvs-health': 'CVS',
  netflix: 'NFLX',
  spotify: 'SPOT',
  'disney-plus': 'DIS',
  hulu: 'DIS',
  'walt-disney-company': 'DIS',
  verizon: 'VZ',
  chase: 'JPM',
  'jpmorgan-chase': 'JPM',
  'bank-of-america': 'BAC',
  'wells-fargo': 'WFC',
  'capital-one': 'COF',
  geico: 'BRK-B',
  'berkshire-hathaway': 'BRK-B',
  'planet-fitness': 'PLNT',
};
export const SAMPLE_TICKERS = [...new Set(Object.values(SAMPLE_TICKER_MAP))];
